### ISSUE TITLE
More specs on each of the model

### ISSUE THREAD

**Issue by arkilis** [lowsideio/data#2]
Hi all,

I am a motorbike lover, is there any more specs on each of the model, i.e. engine size, strokes and so on?

Thanks,

**Comment by AkselsLedins** [comment]
Hi,

Yes, actually we have quite a lot of information.
See the Go model : https://github.com/lowsideio/core/blob/master/models/motorcycle.go

I don't have a lot of time to invest in this project but I will buy some cheap domain to run it again as I didn't renew the `lowside.io` (all these .io quickly become expensive)

**Comment by AkselsLedins** [comment]
bought the domain again

![screenshot from 2018-10-19 21-57-51](https://user-images.githubusercontent.com/18367406/47240881-0a18b700-d3ea-11e8-835d-a40cf44a0723.png)

project will be back on tracks soon
